### ISSUE TITLE
Suggestions for improving the spelling and structure of English texts

### ISSUE THREAD

**Issue by IngrownMink4** [adenlall/salatok#26]
### The problem
I took a look at the website and saw that there were quite a few typos in the UI text. I have compiled the errors I have seen so you know what they are (and I've also listed them to save you some work). The good thing is that it's something easy to fix :)

### My suggestions
1) _"ChangLog"_ (old) -> "Changelog" (new)

2) _"Welcome there"_ (old) -> "Welcome to Salatok!" (new)

3) _"Find your Location"_ (old) -> "Find your location" (new)

4) _"We could not determine your location maybe because of the ad blocker or the browser itself, its ok, but you shoud select your location manually, or whitelist the website in your adblocker setting; we dont track you or show you any ads."_ (old) -> "Sorry, but we have not been able to determine your location. Maybe it's because you have your ad-blocker enabled. Try disabling it temporarily and try again. If not, you can enter your location manually or add this page to your whitelist. We don't track you or show you ads anyway, so disabling the ad blocker won't make your experience any worse." (new)

5) _"The reciter :"_ (old) -> "The reciter:" (new)

6) _"It's Free Open Source software, Support Us :"_ (old) -> "It's Free and Open Source software, so you can contribute on GitHub and support us!" (new) 

**Screenshots**

![salatokappold](https://github.com/adenlall/salatok/assets/25466522/0070d4c1-ea23-410e-8162-60f97481ac20)

![salatakappoldtext2](https://github.com/adenlall/salatok/assets/25466522/ea02f57b-785f-4bee-bff5-435e0027afbb)

![salatakappoldtext3](https://github.com/adenlall/salatok/assets/25466522/921f388d-9368-455c-82af-2a397da6ef89)

**Desktop (please complete the following information):**
 - OS: Manjaro GNOME v45
 - Browser: Firefox
 - Version: 124.0.1

**Comment by adenlall** [comment]
Yeah, Cool I already merge your pull request

**Comment by IngrownMink4** [comment]
> For the rest I will look at them in the next commit and correct them

Great 👍🏼
